"""dados table

Revision ID: 5f6300a4a7f0
Revises: 
Create Date: 2019-11-07 09:58:59.601667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6300a4a7f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_num', sa.Integer(), nullable=True),
    sa.Column('timedelta', sa.Float(), nullable=True),
    sa.Column('age_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados')
    # ### end Alembic commands ###
